### ISSUE TITLE
System Testing

### ISSUE THREAD

**Issue by remstef** [uhh-lt/autolinks#64]
This issue for testing system

- Mainnav
   - Start with collapsed services in Mainnav
   - Settings Button is without function
   - Header in Mainnav takes too much space -> reduce
   - Order available annotation types alphabetically
   - Order documents alphabetically
   - reduce space between documents in list

- Grid Controller
   - remove buttons without function
   - delete, add, edit

- Upload
   - Uploading of empty documents gives error
   - Whats the filter for uploading documents? (.txt, .py, .sh seem possible, no suffix is impossible to select, either allow only txt, or remove filter, document should be rejected by the backend then)

- Visualization:
   - sentence indicator overlays the sentence for log sentences 
   - sometimes navigating through sentences is not possible anymore (only first sentence stays visible)
   - connecting nodes is not working  (drawing a relation)
   - moving nodes into another compound node is not possible
   - collapsing a compound node is sometimes not possible (button is not available)
   - collapsing / uncollapsing changes zooms in / out (user losses focus)
   - searching for new terms/ clicking on an annotation opens new graph at random positions (zooms in / out + user losses focus)
   - after clicking on an annotation source of a node, clicking on an underlined text doesn't resolve to its annotations but only queries the services
   - selecting an annotation from the second sentence onwards gives wrong text -> offset is calculated only from the first sentence
   
- Resource properies view (on the right)
   - when metadata is collapsed, the respective Buttons should also be collapsed
   - make sources unique (no duplicates)

- Minor things:
   - Circlenav changes symbol when clicking -> unnecessary (the one with one wheel is visually clearer, why?)
   - Opening/ Closing of search bar is not necessary, it can always be there 
   
- Probably related:
   - while playing around, I received the following error messages

```
TypeError: Cannot read property 'name' of undefined
    at module.exports (/opt/project/frontendserver/api/service/call.js:2:21)
    at call (/opt/project/frontendserver/api/service/serviceEndpoint.js:35:21)
    at Layer.handle [as handle_request] (/opt/project/frontendserver/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/project/frontendserver/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/project/frontendserver/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/project/frontendserver/node_modules/express/lib/router/layer.js:95:5)
    at /opt/project/frontendserver/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/opt/project/frontendserver/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/project/frontendserver/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/opt/project/frontendserver/node_modules/express/lib/router/index.js:174:3)

TypeError: Cannot read property 'mv' of undefined
    at postDocuments (/opt/project/frontendserver/api/storage/storageEndpoint.js:63:10)
    at Layer.handle [as handle_request] (/opt/project/frontendserver/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/project/frontendserver/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/project/frontendserver/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/project/frontendserver/node_modules/express/lib/router/layer.js:95:5)
    at /opt/project/frontendserver/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/opt/project/frontendserver/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/project/frontendserver/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/opt/project/frontendserver/node_modules/express/lib/router/index.js:174:3)
    at router (/opt/project/frontendserver/node_modules/express/lib/router/index.js:47:12)

TypeError: Cannot read property 'name' of undefined
    at module.exports (/opt/project/frontendserver/api/service/call.js:2:21)
    at call (/opt/project/frontendserver/api/service/serviceEndpoint.js:35:21)
    at Layer.handle [as handle_request] (/opt/project/frontendserver/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/project/frontendserver/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/project/frontendserver/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/project/frontendserver/node_modules/express/lib/router/layer.js:95:5)
    at /opt/project/frontendserver/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/opt/project/frontendserver/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/project/frontendserver/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/opt/project/frontendserver/node_modules/express/lib/router/index.js:174:3)
```

**Comment by remstef** [comment]
See also https://github.com/uhh-lt/autolinks/wiki/System-Testing-Workflow

**Comment by alvinrindra** [comment]
Hi @remstef, my current commits and merges to the master fix some bugs, and add new feature 'merge Nodes To Compound'. At the moment it works in the frontend, but unfortunately, it only saves one node in the backend. What I mean here, if we create new nodes with one compound, the backend only saves the compound one, not with its children. We can discuss further later when I come to the office.

**Comment by remstef** [comment]
- Document Handling:
   - [ ] Document deletion should also remove the currently active sentences (document lense) 
   - [ ] re-uploading fails (its uploaded but server chrashes) see error message:
      - show loading indicator!
```
fs.js:1081
  return binding.unlink(pathModule.toNamespacedPath(path));                                            
                 ^

Error: ENOENT: no such file or directory, unlink './uploads/Tcell.txt'                                 
    at Object.fs.unlinkSync (fs.js:1081:18)
    at Request._callback (/opt/project/frontendserver/api/storage/storageEndpoint.js:95:12)            
    at Request.self.callback (/opt/project/frontendserver/node_modules/request/request.js:185:22)      
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/opt/project/frontendserver/node_modules/request/request.js:1157:10)       
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/opt/project/frontendserver/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! autolinks@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the autolinks@1.0.0 start script.                                                   
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.     


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.5.1 → 6.2.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:                                                   
npm ERR!     /root/.npm/_logs/2018-07-19T13_32_23_445Z-debug.log 
```

- Visualiztion test (search)
   - service + search bcell fails

**Comment by alvinrindra** [comment]
[ ] Add how to / guides inside app?

**Comment by alvinrindra** [comment]
Hi @remstef , I have an issue for the backend. You now update every same label node with different rids.

This is what 'B cell' demo looks like if the rids are different.

![image](https://user-images.githubusercontent.com/8433469/44006393-343c4c40-9e84-11e8-8d89-94286c641248.png)
